### ISSUE TITLE
Thanks for the great work! I would like to ask if you can publish the code and dataset of the paper?

### ISSUE THREAD

**Issue by dante1024** [dddraxxx/Weakly-Supervised-Camouflaged-Object-Detection-with-Scribble-Annotations#1]
Hi! I read your paper "Weakly-Supervised Camouflaged Object Detection with Scribble Annotations", Thanks for the great work! I would like to ask if you can publish the code and dataset of the paper?

**Comment by dddraxxx** [comment]
They are released. Feel free to use.
