### ISSUE TITLE
关于Fss特征图的一些问题

### ISSUE THREAD

**Issue by 2394855029** [dddraxxx/Weakly-Supervised-Camouflaged-Object-Detection-with-Scribble-Annotations#12]
您好，最近在拜读您的论文时，对论文中提及的Fss特征图有一些问题想向您请教：
（1）Fss(semantic feature map/intermediate feature map)是在CRNet的倒数第二层得到的吗？(根据文中给出的CRNet结构图，我看到Fss是由最后提取出的Fout0特征和Fout1特征进行fusion操作得到的，所以我对文中后续提到的Fss is extracted before the final prediction layer比较困解)
![7TD%(2ZJPJ7N7{NH{Q}Y5HV](https://github.com/dddraxxx/Weakly-Supervised-Camouflaged-Object-Detection-with-Scribble-Annotations/assets/78649913/e8ef7fd3-995d-4cf8-8416-ceb34bdf598b)
（2）文中提到，需要停止Fss的梯度，我不太理解这里的含义和这样做的意义(从文中可以知道，提取Fss是用来计算SS loss)
（3）根据文章可以知道，Pi表示的是像素i为前景的概率，为什么Pi的计算是用Fss的每个通道对应的像素位置的值做累和来计算得到(除了Fss，可不可以用其他的feature map来这样做呢)？

期待您的回复，不甚感激。

**Comment by dddraxxx** [comment]
(1) 细节请参考code。
(2) 不stop的话可能会让feature map的学习受到预测结果的负面影响
(3) 其他feature map可能也可以。

**Comment by 2394855029** [comment]
> (1) 细节请参考code。 (2) 不stop的话可能会让feature map的学习受到预测结果的负面影响 (3) 其他feature map可能也可以。

非常感谢您的耐心解答我的问题。您的帮助对我非常有帮助。

**Comment by dddraxxx** [comment]
不客气
