### ISSUE TITLE
关于文章标题的疑惑

### ISSUE THREAD

**Issue by 2394855029** [dddraxxx/Weakly-Supervised-Camouflaged-Object-Detection-with-Scribble-Annotations#13]
您好，在拜读您的文章时，我发现这篇文章最后输出的是分割的结果，但文章标题中所提及的任务是object detection。所以想向您请教一下，COD方法是否是做的分割任务，为什么要定义为目标检测呢？
期待您的回复，不甚感激。

**Comment by dddraxxx** [comment]
大家都这么叫的
