### ISSUE TITLE
Question about  Results on NC4K

### ISSUE THREAD

**Issue by YangLiFena** [dddraxxx/Weakly-Supervised-Camouflaged-Object-Detection-with-Scribble-Annotations#15]
Thank you very much for your work. May I ask if it is possible to release the prediction results of DUSD (Zhang et al 2018), USPS (Nguyen et al 2019), SS (Zhang et al 2020b), and SCWSSOD (Yu et al 2021) on the NC4K benchmark?

**Comment by dddraxxx** [comment]
We have provided our results. For others, you might need to ask for the author.
