### ISSUE TITLE
ask for optimization 

### ISSUE THREAD

**Issue by ghost** [dddraxxx/Weakly-Supervised-Camouflaged-Object-Detection-with-Scribble-Annotations#18]
hello. I want to work on your paper and add a module for texture segmentation, a different module, can you help me how can I do it?

**Comment by dddraxxx** [comment]
Sorry but I can't help much in texture segmentation.

**Comment by ghost** [comment]
just guide me then I research more, as your knowledge just helps which architecture can be helpful to this?

**Comment by dddraxxx** [comment]
The [paper](https://arxiv.org/abs/2207.14083) contains the idea of the network design. You may refer to it.

**Comment by fa3ima95** [comment]
could you help how to fix this matter,  I want to generate more datasets and use your model when I do scribble an RGB image on interested area , absolutely I should have an RGB image with 2 lines, one for background another for foreground, then with python script, I convert this image to an image in a range of ( 0,1,2). but here is the matter, the result is a blank image when I get the shape it has 3 dimensions but all values of image are zero. can you help me how can I get more datasets with scribble annotations mask.

**Comment by ghost** [comment]
hello dude again:))

Is there any idea to make the result better that you can say? (for example, add a special module or add more layers to proposed module.)
