### ISSUE TITLE
scribble

### ISSUE THREAD

**Issue by ghost** [dddraxxx/Weakly-Supervised-Camouflaged-Object-Detection-with-Scribble-Annotations#19]
hello 
There is a question, for training your model, when you used scribble annotation as your ground truth, when you give it to network, it would be gray scale ( 0-1-2) or binary mask(0-1)?

**Comment by dddraxxx** [comment]
Tbh I forget it. We did use 0,1,2 in the code but I forgot if they are in the saved scribble images.
