### ISSUE TITLE
train.txt

### ISSUE THREAD

**Issue by xua222** [dddraxxx/Weakly-Supervised-Camouflaged-Object-Detection-with-Scribble-Annotations#2]
FileNotFoundError: [Errno 2] No such file or directory: '../CodDataset/train.txt'

**Comment by dddraxxx** [comment]
It includes all the images in COD10K-train. You may check it here for your reference.
[train.txt](https://github.com/dddraxxx/Weakly-Supervised-Camouflaged-Object-Detection-with-Scribble-Annotations/files/10349348/train.txt)
