### ISSUE TITLE
About Eq.(2) proposed in the paper...

### ISSUE THREAD

**Issue by Liyuan0905** [dddraxxx/Weakly-Supervised-Camouflaged-Object-Detection-with-Scribble-Annotations#20]
Hello,

This is an interesting paper, but I encountered some issues while studying it.

In the paper, the context affinity loss \(L_{ca}\) encourages visually dissimilar pixels to have different labels, and vice versa, as stated in Equations (2) and (3). 

However, in the code (specifically in `feature_loss.py` and `train_processes.py`), the predictions obtained from the model are used without any additional operations. How is the operation proposed in Equation (2) represented in the code?

Thank you!

**Comment by dddraxxx** [comment]
It is somewhere in the code. But not the same name as in the paper. I think you can pay attention to [here](https://github.com/dddraxxx/Weakly-Supervised-Camouflaged-Object-Detection-with-Scribble-Annotations/blob/944eed179d97599144460ed535c505a00bc0ff3c/train_processes.py#L9C1-L10C1), which give the args of the visual kernel.

**Comment by Liyuan0905** [comment]
Could you please clarify how Equ. (2) is implemented in the code? 

I reviewed the feature_loss.py file and noticed that D(i, j) is defined as p_{i} - p_{j}, which appears to be equivalent to the Local Saliency Coherence Loss as introduced in the SCWSSOD  (Structure-Consistent Weakly Supervised Salient Object Detection with Local Saliency Coherence). However, this seems to differ from what is described in Equ. (2). I am concerned that there might be an oversight or a misunderstanding.

Thank you!

**Comment by dddraxxx** [comment]
1. The loss actually originates from _Gated CRF Loss for Weakly Supervised Semantic Image Segmentation_, and is widely adopted by numerous weakly supervised papers.
2. I don't know what you are referring. It will be easier for me to check if you could include the link to code in your question. Thanks.
