### ISSUE TITLE
Results on NC4K

### ISSUE THREAD

**Issue by GewelsJI** [dddraxxx/Weakly-Supervised-Camouflaged-Object-Detection-with-Scribble-Annotations#3]
Hi, @dddraxxx 

Could you please provide the prediction results on NC4K dataset?

Thanks.

**Comment by dddraxxx** [comment]
We provide the the code and model weight so you may test it in any dataset you want.

**Comment by GewelsJI** [comment]
Hi, @dddraxxx 

Sorry to bother you again. I have a question about how to inference with your model.

When I run test.py, I got a bug here:

```
RuntimeError: Error(s) in loading state_dict for Net:
        Unexpected key(s) in state_dict: "rw.gamma", "rw.query_conv.weight", "rw.query_conv.bias", "rw.key_conv.weight", "rw.key_conv.bias", "rw.value_conv.weight", "rw.value_conv.bias", "ca.0.conv1.weight", "ca.0.conv1.bias", "ca.0.bn1.weight", "ca.0.bn1.bias", "ca.0.bn1.running_mean", "ca.0.bn1.running_var", "ca.0.bn1.num_batches_tracked", "ca.0.conv_h.weight", "ca.0.conv_h.bias", "ca.0.conv_w.weight", "ca.0.conv_w.bias", "ca.1.conv1.weight", "ca.1.conv1.bias", "ca.1.bn1.weight", "ca.1.bn1.bias", "ca.1.bn1.running_mean", "ca.1.bn1.running_var", "ca.1.bn1.num_batches_tracked", "ca.1.conv_h.weight", "ca.1.conv_h.bias", "ca.1.conv_w.weight", "ca.1.conv_w.bias", "ca.2.conv1.weight", "ca.2.conv1.bias", "ca.2.bn1.weight", "ca.2.bn1.bias", "ca.2.bn1.running_mean", "ca.2.bn1.running_var", "ca.2.bn1.num_batches_tracked", "ca.2.conv_h.weight", "ca.2.conv_h.bias", "ca.2.conv_w.weight", "ca.2.conv_w.bias", "ca.3.conv1.weight", "ca.3.conv1.bias", "ca.3.bn1.weight", "ca.3.bn1.bias", "ca.3.bn1.running_mean", "ca.3.bn1.running_var", "ca.3.bn1.num_batches_tracked", "ca.3.conv_h.weight", "ca.3.conv_h.bias", "ca.3.conv_w.weight", "ca.3.conv_w.bias", "ca.4.conv1.weight", "ca.4.conv1.bias", "ca.4.bn1.weight", "ca.4.bn1.bias", "ca.4.bn1.running_mean", "ca.4.bn1.running_var", "ca.4.bn1.num_batches_tracked", "ca.4.conv_h.weight", "ca.4.conv_h.bias", "ca.4.conv_w.weight", "ca.4.conv_w.bias", "edge_extract.0.weight", "edge_extract.0.bias", "edge_extract.1.weight", "edge_extract.1.bias", "edge_extract.1.running_mean", "edge_extract.1.running_var", "edge_extract.1.num_batches_tracked", "edge_extract.3.weight", "edge_extract.3.bias", "edge_extract.4.weight", "edge_extract.4.bias", "edge_extract.4.running_mean", "edge_extract.4.running_var", "edge_extract.4.num_batches_tracked".
```

I further check the net.py, and I also find some extra unused modules such as [edge_head](https://github.com/dddraxxx/Weakly-Supervised-Camouflaged-Object-Detection-with-Scribble-Annotations/blob/main/net.py#L409). Could you help me on this problem?

Thanks
Ge-Peng.

**Comment by dddraxxx** [comment]
> Hi, @dddraxxx
> 
> Sorry to bother you again. I have a question about how to inference with your model.
> 
> When I run test.py, I got a bug here:
> 
> ```
> RuntimeError: Error(s) in loading state_dict for Net:
>         Unexpected key(s) in state_dict: "rw.gamma", "rw.query_conv.weight", "rw.query_conv.bias", "rw.key_conv.weight", "rw.key_conv.bias", "rw.value_conv.weight", "rw.value_conv.bias", "ca.0.conv1.weight", "ca.0.conv1.bias", "ca.0.bn1.weight", "ca.0.bn1.bias", "ca.0.bn1.running_mean", "ca.0.bn1.running_var", "ca.0.bn1.num_batches_tracked", "ca.0.conv_h.weight", "ca.0.conv_h.bias", "ca.0.conv_w.weight", "ca.0.conv_w.bias", "ca.1.conv1.weight", "ca.1.conv1.bias", "ca.1.bn1.weight", "ca.1.bn1.bias", "ca.1.bn1.running_mean", "ca.1.bn1.running_var", "ca.1.bn1.num_batches_tracked", "ca.1.conv_h.weight", "ca.1.conv_h.bias", "ca.1.conv_w.weight", "ca.1.conv_w.bias", "ca.2.conv1.weight", "ca.2.conv1.bias", "ca.2.bn1.weight", "ca.2.bn1.bias", "ca.2.bn1.running_mean", "ca.2.bn1.running_var", "ca.2.bn1.num_batches_tracked", "ca.2.conv_h.weight", "ca.2.conv_h.bias", "ca.2.conv_w.weight", "ca.2.conv_w.bias", "ca.3.conv1.weight", "ca.3.conv1.bias", "ca.3.bn1.weight", "ca.3.bn1.bias", "ca.3.bn1.running_mean", "ca.3.bn1.running_var", "ca.3.bn1.num_batches_tracked", "ca.3.conv_h.weight", "ca.3.conv_h.bias", "ca.3.conv_w.weight", "ca.3.conv_w.bias", "ca.4.conv1.weight", "ca.4.conv1.bias", "ca.4.bn1.weight", "ca.4.bn1.bias", "ca.4.bn1.running_mean", "ca.4.bn1.running_var", "ca.4.bn1.num_batches_tracked", "ca.4.conv_h.weight", "ca.4.conv_h.bias", "ca.4.conv_w.weight", "ca.4.conv_w.bias", "edge_extract.0.weight", "edge_extract.0.bias", "edge_extract.1.weight", "edge_extract.1.bias", "edge_extract.1.running_mean", "edge_extract.1.running_var", "edge_extract.1.num_batches_tracked", "edge_extract.3.weight", "edge_extract.3.bias", "edge_extract.4.weight", "edge_extract.4.bias", "edge_extract.4.running_mean", "edge_extract.4.running_var", "edge_extract.4.num_batches_tracked".
> ```
> 
> I further check the net.py, and I also find some extra unused modules such as [edge_head](https://github.com/dddraxxx/Weakly-Supervised-Camouflaged-Object-Detection-with-Scribble-Annotations/blob/main/net.py#L409). Could you help me on this problem?
> 
> Thanks Ge-Peng.

Sorry for the mistake. I have uploaded the code and a correct version of [model_weight](https://drive.google.com/file/d/1YrtwLNAbXkk162YOwweS9-QwTzovG7xI/view?usp=sharing). Please use it instead.

**Comment by GewelsJI** [comment]
Thanks. But how to make a txt list for testing?

https://github.com/dddraxxx/Weakly-Supervised-Camouflaged-Object-Detection-with-Scribble-Annotations/blob/main/data/dataset.py#L76

**Comment by dddraxxx** [comment]
> Thanks. But how to make a txt list for testing?
> 
> https://github.com/dddraxxx/Weakly-Supervised-Camouflaged-Object-Detection-with-Scribble-Annotations/blob/main/data/dataset.py#L76

You can refer to [this](https://github.com/dddraxxx/Weakly-Supervised-Camouflaged-Object-Detection-with-Scribble-Annotations/issues/2#issuecomment-1371772695) in #2
