### ISSUE TITLE
Here are some questions, why the weakly supervised dataset Scribble you provided is all black?

### ISSUE THREAD

**Issue by dante1024** [dddraxxx/Weakly-Supervised-Camouflaged-Object-Detection-with-Scribble-Annotations#4]
Thanks for the great work! Here are some questions, why the weakly supervised dataset Scribble you provided is all black?

**Comment by dddraxxx** [comment]
The labels have values of 0,1,2 but the image has values of 0-255, so it is "black" when you view the label as images.
