### ISSUE TITLE
LSR Module中激活函数的相关问题

### ISSUE THREAD

**Issue by yeqian1961** [dddraxxx/Weakly-Supervised-Camouflaged-Object-Detection-with-Scribble-Annotations#5]
您好，最新拜读您的论文时，在Supplementary Material中的Logical Semantic Relation (LSR) Module发现您在论文中提及最后的输出时用GeLU函数激活，但在net.py文件中，LSR模块最后依旧是使用ReLU模块激活。另外，我想请问一下您是根据什么来决定使用GeLU还是ReLU激活的呢？
![image](https://user-images.githubusercontent.com/58923780/228710698-0c24c3a1-7fb5-430c-bdab-78523fa2822a.png)
![image](https://user-images.githubusercontent.com/58923780/228710655-b444e170-0879-4c51-8d21-2c95631a2de1.png)
静候您的回复，不甚感激。

**Comment by Catherine-R-He** [comment]
Thank you for your interest. You are correct; it's a typo. However, please kindly note that both Figure 4 and the formula below the paragraph you referred to write "ReLU". 

Cheers!
