### ISSUE TITLE
数据集中图片全部为黑色，没有期待中的涂鸦注释

### ISSUE THREAD

**Issue by LiuMingYy** [dddraxxx/Weakly-Supervised-Camouflaged-Object-Detection-with-Scribble-Annotations#8]
非常感谢您的工作！在对您的代码进行复现时，我发现项目中提供的数据集S-COD中的图片似乎被损坏了。如果方便的话，您能否检查并重新上传S-COD数据集呢？万分感谢！

**Comment by dddraxxx** [comment]
The image is from 0-255 and the annotation is 0,1,2. Please check again

**Comment by LiuMingYy** [comment]
问题已解决，感谢您的回复！
