### ISSUE TITLE
Scribble Dataset

### ISSUE THREAD

**Issue by moktsuiqin** [dddraxxx/Weakly-Supervised-Camouflaged-Object-Detection-with-Scribble-Annotations#9]
I have some questions to ask you about the scribble dataset. First, can I know which software did you use to generate the scribble dataset. Second, I assume that the scribble picture at first is in RGB image, how do you convert it to 0-255 range with png extension which you uploaded your scribble dataset here.

**Comment by Catherine-R-He** [comment]
Hi, thanks for your interest. 

The annotation process is very similar to those on semantic segmentation datasets. The only difference is that we only annotated two lines (scribbles) while segmentation annotation is usually in regions. Hence, any annotation tool for segmentation could be used for scribble annotation.

Though the images are in three channels (RGB), when you annotate them to categories in annotation tools/platforms, the ground truth will be saved with class labels automatically. In other words, each pixel position will be assigned a value within the category value domain. In our case, "1" stands for foregrounds, "2" for backgrounds, and "0" for unlabeled regions.
